# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghir" do
  name "ghir"
  desc "ghir is a CLI making GitHub Releases immutable"
  homepage "https://github.com/suzuki-shunsuke/ghir"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghir"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghir/releases/download/v#{version}/ghir_darwin_amd64.tar.gz"
      sha256 "010c06f05ff9547914fb53c8c205a067b8c2d088fdd73ca00d969438f123e6ef"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghir/releases/download/v#{version}/ghir_darwin_arm64.tar.gz"
      sha256 "254a5943f2d100ae5dd91685fe49e64d45336544e2d8d45a7d5fbeaad3eff841"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghir/releases/download/v#{version}/ghir_linux_amd64.tar.gz"
      sha256 "64d8c6f3e18c6f2b334c9e548b0888bd66a543e73daed7b1c5c6a3a49f835bad"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghir/releases/download/v#{version}/ghir_linux_arm64.tar.gz"
      sha256 "9cadb4d016ceb13482df97972bd5fe4622244486639c24d27df39eb5f31e30d7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghir"]
    end
  end

  # No zap stanza required
end
