# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghir" do
  name "ghir"
  desc "ghir is a CLI making GitHub Releases immutable"
  homepage "https://github.com/suzuki-shunsuke/ghir"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghir"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghir/releases/download/v#{version}/ghir_darwin_amd64.tar.gz"
      sha256 "28a3508d776437cb0f0d1b794307f3ba588edfea95e194e48531a4cc8227639a"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghir/releases/download/v#{version}/ghir_darwin_arm64.tar.gz"
      sha256 "b530c865e6fda1212beb5ad7561411d3e64c59dd2945ace20b434838c4fd5e79"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghir/releases/download/v#{version}/ghir_linux_amd64.tar.gz"
      sha256 "338cefcb0bd1064d0bd0bafe38f67ff3fda2d3a8a0fb23db52e3e99c2a102b84"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghir/releases/download/v#{version}/ghir_linux_arm64.tar.gz"
      sha256 "47b56d04cc2e2a6c162db64c243202e31ce7ec6bddde74df5925c985901853a1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghir"]
    end
  end

  # No zap stanza required
end
