# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghir" do
  name "ghir"
  desc "ghir is a CLI making GitHub Releases immutable"
  homepage "https://github.com/suzuki-shunsuke/ghir"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghir"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghir/releases/download/v#{version}/ghir_darwin_amd64.tar.gz"
      sha256 "eb672dc38256f624bd5f0a195dee11de6fb7b1a6dfeb53877c97dd39e9625ff4"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghir/releases/download/v#{version}/ghir_darwin_arm64.tar.gz"
      sha256 "703c01def9c996d4e91dd15b721f25735176d0548163f486c0da462e064ba15b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghir/releases/download/v#{version}/ghir_linux_amd64.tar.gz"
      sha256 "13c3bc34b61116547a3b90d528220b318c47ea9a1f9553aeba24f394c513e461"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghir/releases/download/v#{version}/ghir_linux_arm64.tar.gz"
      sha256 "5c87c3502a92ed590fd0a1f5afce83204ec029ba717b9439703a7c0944c82d4a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghir"]
    end
  end

  # No zap stanza required
end
